module.exports = {
	FIRST_NAME_REQUIRED: 'FIRST_NAME_REQUIRED',
	EMAIL_REQUIRED: 'EMAIL_REQUIRED',
	LAST_NAME_REQUIRED: 'LAST_NAME_REQUIRED',
	PHONE_NUMBER_REQUIRED: 'PHONE_NUMBER_REQUIRED',

	FIRST_NAME_NOT_A_STRING: 'FIRST_NAME_NOT_A_STRING',
	EMAIL_NOT_A_STRING: 'EMAIL_NOT_A_STRING',
	LAST_NAME_NOT_A_STRING: 'LAST_NAME_NOT_A_STRING',
	PHONE_NUMBER_NOT_A_STRING: 'PHONE_NUMBER_NOT_A_STRING',
	PHONE_NUMBER_ONLY_NUMBERS: 'PHONE_NUMBER_ONLY_NUMBERS',


	WRONG_EMAIL_FORMAT: 'WRONG_EMAIL_FORMAT',
};
